```mermaid
sequenceDiagram;
    participant C as Client
    participant O as Resource Owner
    participant A as Authorization Server
    participant R as Resource Server
    
    C->>O: requests authorization 
    O->>C: receives authorization grant
    C->>A: requests access token, presents grant
    A->>C: authenticates client, validates grant, issues access token
    C->>R: requests protected resource, presents access token
    R->>C: validates access token, serves request
```
    